### ISSUE TITLE
After installation of the driver my steam deck sees only 5G networks. 

### ISSUE THREAD

**Issue by OdinDmitry** [ryanrudolfoba/SteamDeckWindowsFixForWiFi#5]
Any assumptions why it can happen?

**Comment by ryanrudolfoba** [comment]
> Any assumptions why it can happen?

that's normal behavior because the script i did it changes the settings so it only sees 5GHz networks as that is the one that works good in my environment.

You can manually change the setting back so it sees both 2.4 and 5GHz network -

go to Device Manager > RTK Killer Wifi > Advance

scroll all the way down and change the option for Wireless Mode.

**Comment by OdinDmitry** [comment]
Changed from Auto to 802.11ac/b/g and it works now, thank you! And thank you for your work! :)
